config/routes.rb
Rails3MongoidOmniauth::Application.routes.draw do
  resources :users, :only => :show

  root :to => 'home#index'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#destroy'
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#new', :as => :signin
end

app/models/tweet.rb
class Tweet
  include Mongoid::Document
end

app/models/user.rb
class User
	include Mongoid::Document
	field :provider, :type => String
	field :uid, :type => String
	field :name, :type => String
	field :email, :type => String

	attr_protected :provider, :uid, :name, :email

	def self.create_with_omniauth(auth)
		create! do |user|
			user.provider = auth['provider']
			user.uid = auth['uid']
			if auth['info']
				user.name = auth['info']['name'] || ""
				user.email = auth['info']['email'] || ""
			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private 
  	def current_user
  		begin
  			@current_user ||= User.find(session[:user_id]) if session[:user_id]
  		rescue Mongoid::Errors::DocumentNotFound
  			nil
  		end
  	end

  	def user_signed_in?
  		return true if current_user
  	end

  	def correct_user? 
  		@user = User.find(params[:id])
  		unless current_user == @user
  			redirect_to root_url, :alert => "Access denied."
  		end
  	end

  	def authenticate_user!
  		if !current_user
  			redirect_to root_url, :alert => "You need to sign in to access this page."
  		end
  	end
  	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@users = User.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
	  auth = request.env["omniauth.auth"]
	  provider = auth['provider']
	  uid = auth['uid']

	  user = User.where(:provider => provider, :uid => uid).first

	  user ||= User.create_with_omniauth(auth)
	  session[:user_id] = user.id
	  redirect_to root_url, :notice => "Signed in!"
	end

	def destroy
		reset_session
		redirect_to root_url, :notice => "Signed out!"
	end	

	def new
		redirect_to '/auth/twitter'
	end

	def failure
		redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%h1 Home is Where The Heat Is!
- @users.each do |user|
	%p 
		User: 
		= link_to user.name, user

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title OmniAuth To The Limit
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
  %body
    #container.container
      %header
        = render 'shared/navigation'
      #main{:role => "main"}
        = yield
      %footer

app/views/shared/_navigation.html.haml
- if user_signed_in? 
  %li
    Logged in as 
    = current_user.name 
  %li
    = link_to('Logout', signout_path)
  
- else 
  %li
    = link_to('Login', signin_path)

app/views/users/show.html.haml
%h3 User Profile
%p
	Name:
	= @user.name
%p 
	Email:
	= @user.email if @user.email